query GetAccreditationByUser {
  getAccreditationByUser {
    _id
    categoryId
    subcategoryId
    userId
    accredited
    isDeleted
    status
    dateAccredited
    dateCreated
    expiryDate
    proofOfPayment
    supportingDocument
    category {
      _id
      name
    }
    subcategory {
      name
    }
    user {
      nameOfCompany
    }
  }
}

