query GetAccreditations {
  getUser {
    _id
    accreditation {
      id
      categoryId
      subCategoryId
      userId
      accredited
      isDeleted
      status
      dateAccredited
      expiryDate
      proofOfPayment
      supportingDocument
    }
  }
}

