query GetAccreditation($id: String!) {
  getAccreditation(id: $id) {
    categoryId
    subcategoryId
    userId
    accredited
    isDeleted
    status
    dateAccredited
    dateCreated
    expiryDate
    dateCreated
    proofOfPayment
    supportingDocument
    category {
      _id
      name
    }
    subcategory {
      name
    }
    user {
      nameOfCompany
    }
  }
}
