query GetCompany {
  getUser {
    _id
    nameOfCompany
    location
    address
    rcNumber
    dateOfIncorporation
    tin
    phoneNumber

    certificateOfIncorporation
    certificateOfTaxClearance
    applicationLetter
    evidenceOfPayment
    letterOfCredibilityFromBanks
    collaborationCertificateWithForeignPartners
    curriculumVitae{
      file
      title
    }
    boardOfDirectors{
      file
      title
    }
    profilePic
  }
}

